/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

//引入Hello.h
#include "Hello.h"
/* Header for class com_jnidemo_iv_JniUtil */

#ifndef _Included_com_jnidemo_iv_JniUtil
#define _Included_com_jnidemo_iv_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnidemo_iv_JniUtil
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jnidemo_1iv_JniUtil_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
